### ISSUE TITLE
Can we run `dotstow sync` in just clone only mode without granting write access to the repo ?

### ISSUE THREAD

**Issue by sreerajkksd** [codejamninja/dotstow#8]
I want to setup a new computer with dotfiles without the need of writing any changes from that computer. Think of it as a secondary computer to me.

Looks like we need to setup ssh-agent keys to have the initial clone done which personally to me a very bad idea. I should be able to clone a public repo without actually requesting anything. That would also allow me to try other users dotfiles as well.

**Comment by clayrisser** [comment]
When setting up dotstow, you can provide the repo using http protocol instead of ssh.

```
dotstow sync                                 
github username (codejamninja): 
dotfiles remote (git@github.com:codejamninja/dotfiles.git): https://github.com/codejamninja/dotfiles.git
```

However like you mentioned, it tries to commit any new changes and push them during sync.
https://github.com/codejamninja/dotstow/blob/master/src/actions/sync.ts#L25
https://github.com/codejamninja/dotstow/blob/master/src/actions/sync.ts#L29

I think the best approach would be to create a new command called `pull` that only pulls the dotfiles.

What are your thoughts?

**Comment by clayrisser** [comment]
I just created a basic pull request that would achieve something similar to what you want. We would need to first figure out how to handle any modified files though.

https://github.com/codejamninja/dotstow/pull/9/files#diff-a8e6e270f2910fc45939f0017baed090R16

**Comment by sreerajkksd** [comment]
yeah, creating a new `pull` command makes sense and would be simpler. 

To catch the changed files, we can store the last commit before doing a pull and do `git diff --name-only SHA1 HEAD`

**Comment by clayrisser** [comment]
@sreerajkksd would you mind submitting a pull request for that?

**Comment by sreerajkksd** [comment]
Yeah, I can do that once https://github.com/codejamninja/dotstow/pull/9 is merged to master.

**Comment by clayrisser** [comment]
@sreerajkksd I just merged it.

**Comment by clayrisser** [comment]
This should work because it pulls first (although it might give an error status).
